coffeenet:
  application-name: CoffeeNet Frontpage
  profile: development
  security:
    client:
      client-id: coffeeNetClient
      client-secret: coffeeNetClientSecret
  logging:
    console:
      enabled: true
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      username: frontpage
      password: frontpage
      authentication-database: admin
      database: frontpage

frontpage:
    plugins:
      resource:
        - repositoryName: coffeenet/coffeenet-frontpage-plugin-feed
        - repositoryName: coffeenet/coffeenet-frontpage-plugin-influx
